language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libgd2-noxpm-dev
      - libleveldb-dev
      - libhiredis

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_LEVELDB=true -DENABLE_POSTGRESQL=true -DENABLE_REDIS=true

script: 
  - cmake --build . --config Release
