language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libgd2-noxpm-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - cmake --build . --config Release
